<?php
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');

// Ensure that $widgetOptions contains the breadcrumb JSON data
$widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($viewModel->getJsonConfigurationHtmlEscaped());
$widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['breadcrumbs']);
?>
<div class="breadcrumbs">
    <ul>
        <script type="text/javascript">
            var breadcrumbsData = <?= $widgetOptions ?>;
            breadcrumbsData.forEach(function(item) {
                document.write('<li><a href="' + item.link + '">' + item.label + '</a></li>');
            });
        </script>
    </ul>
</div>
